
trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
- stage: 'Maven'
  jobs:
  - job: 'maven'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
  
    - task: CopyFiles@2

      inputs:
        SourceFolder: '$(system.defaultWorkingDirectory)'
        Contents: '**/*.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'ls -al $(Build.ArtifactStagingDirectory)'


  - job: 'docker'
    steps:
    - checkout: None


    - task: Docker@2
      inputs:
        containerRegistry: 'Azure-Dockerhub'
        repository: 'tharunmudiraj/myfirstdocrepo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(Build.ArtifactStagingDirectory)'
    - task: Docker@2
      inputs:
        containerRegistry: 'Azure-Dockerhub'
        command: 'login'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          'docker pull tharunmudiraj/myfirstdocrepo:latest'
                  'docker run  tharunmudiraj/myfirstdocrepo:latest'
    